import { basename } from "node:path";
import { CANONICAL_ACTIONS, type CanonicalAction } from "../config/constants.js";
import {
  MenuDefinitionSchema,
  type Action,
  type Manifest,
  type MenuDefinition,
} from "../manifest/schema.js";

export interface GenerateOptions {
  recentLimit?: number;
}

export interface GenerateAudit {
  mapped: string[];
  preserved: string[];
  hidden: string[];
  extras: number;
  ui: string[];
  /** Canonical actions with no matching script — the project has no dev/build/test/… command. */
  missing: string[];
  /** Definition `overrides` that target an id which is neither a detected script nor an extra. */
  orphans: string[];
}

export interface GeneratedMenuDefinition {
  definition: MenuDefinition;
  audit: GenerateAudit;
}

const NOISY_SCRIPT_IDS = new Set([
  "preinstall",
  "install",
  "postinstall",
  "prepare",
  "menu",
  "menu:navig",
  "prepublish",
  "prepublishOnly",
]);

const CANONICAL_COPY: Record<CanonicalAction, { label: string; description: string }> = {
  dev: { label: "Dev", description: "Start the primary local development workflow." },
  build: { label: "Build", description: "Create the production build artifact." },
  test: { label: "Test", description: "Run the primary test suite." },
  typecheck: { label: "Typecheck", description: "Validate TypeScript types without emitting files." },
  lint: { label: "Lint", description: "Run static analysis and style checks." },
  "lint:fix": { label: "Format / fix", description: "Apply safe formatter or lint fixes." },
  preview: { label: "Preview", description: "Serve the built app locally." },
  start: { label: "Start", description: "Start the production server or default runtime." },
  deploy: { label: "Deploy", description: "Publish or release this project." },
  migrate: { label: "Migrate database", description: "Apply database schema migrations." },
  seed: { label: "Seed database", description: "Load seed data into the database." },
  clean: { label: "Clean", description: "Remove generated files or caches." },
  reset: { label: "Reset", description: "Reset local state or data." },
};

/**
 * Generate the human/AI-owned menu contract from factual detection. Existing values always win:
 * this function only fills gaps, so repeated generation is safe after manual edits.
 */
export function generateMenuDefinition(
  manifest: Manifest,
  existing: MenuDefinition = {},
  opts: GenerateOptions = {},
): GeneratedMenuDefinition {
  const actions: NonNullable<MenuDefinition["actions"]> = { ...(existing.actions ?? {}) };
  const audit: GenerateAudit = {
    mapped: [],
    preserved: [],
    hidden: [],
    extras: existing.extra?.length ?? 0,
    ui: [],
    missing: [],
    orphans: [],
  };

  for (const canonical of CANONICAL_ACTIONS) {
    if (actions[canonical]) {
      audit.preserved.push(canonical);
      continue;
    }
    const candidate = chooseCanonical(manifest.actions, canonical);
    if (!candidate) {
      audit.missing.push(canonical);
      continue;
    }
    actions[canonical] = actionOverride(canonical, candidate);
    audit.mapped.push(`${canonical} -> ${candidate.id}`);
  }

  // Orphans: overrides that curate an id which no longer exists (not detected, not an extra).
  const detectedIds = new Set(manifest.actions.map((a) => a.id));
  const extraIds = new Set((existing.extra ?? []).map((e) => e.id));
  audit.orphans = Object.keys(existing.overrides ?? {}).filter(
    (id) => !detectedIds.has(id) && !extraIds.has(id),
  );

  const hide = mergeUnique(existing.hide ?? [], defaultHiddenScripts(manifest));
  audit.hidden = hide.filter((id) => !(existing.hide ?? []).includes(id));

  // Preserve every existing UI preference (banner toggles, glyphs, density, accent, …) and only
  // fill the core defaults when absent — so "Regenerate" never discards the user's settings.
  const ui = {
    ...existing.ui,
    recentLimit: opts.recentLimit ?? existing.ui?.recentLimit ?? 5,
    showDescriptions: existing.ui?.showDescriptions ?? true,
    showCommandHints: existing.ui?.showCommandHints ?? true,
    footer: existing.ui?.footer ?? "generated by navig-menu",
  };
  audit.ui = Object.entries(ui).map(([key, value]) => `${key}=${String(value)}`);

  const definition = MenuDefinitionSchema.parse({
    $schema: existing.$schema ?? "https://menu.navig.run/schema/v1.json",
    title: existing.title ?? manifest.name ?? basename(manifest.root),
    purpose: existing.purpose ?? manifest.purpose?.value ?? "Project command center",
    accent: existing.accent ?? chooseAccent(manifest),
    packageManager:
      existing.packageManager ??
      (manifest.packageManager.value === "none" ? undefined : manifest.packageManager.value),
    actions,
    hide: hide.length ? hide : undefined,
    extra: existing.extra,
    ui,
    defaultHost: existing.defaultHost,
  });

  return { definition, audit };
}

function chooseCanonical(actions: Action[], canonical: CanonicalAction): Action | undefined {
  const candidates = actions.filter((action) => action.canonical === canonical);
  return candidates.sort((a, b) => scoreCandidate(b, canonical) - scoreCandidate(a, canonical))[0];
}

function scoreCandidate(action: Action, canonical: CanonicalAction): number {
  let score = 0;
  if (action.id === canonical) score += 100;
  if (action.confidence === "explicit") score += 20;
  if (action.confidence === "detected") score += 15;
  if (action.source === "project-scripts") score += 10;
  if (action.cwd === ".") score += 5;
  return score;
}

function actionOverride(canonical: CanonicalAction, action: Action): Exclude<NonNullable<MenuDefinition["actions"]>[string], string> {
  const copy = CANONICAL_COPY[canonical];
  return {
    cmd: commandFor(action),
    label: copy.label,
    description: copy.description,
    risk: action.risk,
    longRunning: action.longRunning,
    group: action.group,
    why: action.why ?? evidenceSummary(action),
  };
}

function commandFor(action: Action): string {
  return [action.launcher, ...action.argv].join(" ").trim();
}

function evidenceSummary(action: Action): string | undefined {
  const first = action.evidence[0];
  if (!first) return undefined;
  return [first.file, first.detail].filter(Boolean).join(" ");
}

function defaultHiddenScripts(manifest: Manifest): string[] {
  return Object.keys(manifest.scripts).filter((id) => NOISY_SCRIPT_IDS.has(id));
}

function mergeUnique(a: string[], b: string[]): string[] {
  return [...new Set([...a, ...b])];
}

function chooseAccent(manifest: Manifest): NonNullable<MenuDefinition["accent"]> {
  const services = new Set(manifest.services.map((service) => service.id));
  const frameworks = new Set(manifest.frameworks.map((framework) => framework.id));
  if (services.has("cloudflare")) return "yellow";
  if (frameworks.has("tauri") || frameworks.has("rust")) return "red";
  if (services.has("stripe")) return "magenta";
  if (frameworks.has("next") || frameworks.has("react") || frameworks.has("vite")) return "cyan";
  return "cyan";
}
