"""`navig audio speed` / `slowed` — the CLI wiring.

The editing itself lives in core (`navig.media.audio_edit`) and is tested in
`core/tests/media/test_audio_edit.py`; a plugin cannot own the tests for a core module.
What IS this plugin's to prove is the wiring: option names, the default output path, and
that a bad rate exits non-zero with a message instead of a traceback.

⚠ This suite runs against the INSTALLED navig, so when the core half of a change has not
been installed yet the module is genuinely absent. That is an environment fact, not a
defect — skip with a reason rather than reporting a failure nobody can act on.
"""

from __future__ import annotations

import shutil
import subprocess
from pathlib import Path

import pytest

pytest.importorskip(
    "navig.media.audio_edit",
    reason="core half not installed yet — run `pip install -e core` (see module docstring)",
)

from navig.media.audio_edit import ffmpeg_available  # noqa: E402

requires_ffmpeg = pytest.mark.skipif(not ffmpeg_available(), reason="ffmpeg not on PATH")


@pytest.fixture()
def tone(tmp_path: Path) -> Path:
    """Two seconds of a real, decodable tone — generated by ffmpeg itself."""
    out = tmp_path / "tone.wav"
    subprocess.run(
        [shutil.which("ffmpeg"), "-nostdin", "-y", "-f", "lavfi",
         "-i", "sine=frequency=440:duration=2", str(out)],
        capture_output=True, check=True, timeout=60,
    )
    return out


def _duration(path: Path) -> float:
    out = subprocess.run(
        [shutil.which("ffprobe"), "-v", "error", "-show_entries", "format=duration",
         "-of", "default=noprint_wrappers=1:nokey=1", str(path)],
        capture_output=True, text=True, check=True, timeout=60,
    )
    return float(out.stdout.strip())


from typer.testing import CliRunner  # noqa: E402

from navig_audio.commands.audio import audio_app  # noqa: E402

runner = CliRunner()


@requires_ffmpeg
def test_speed_verb_writes_a_file_and_does_not_overwrite_the_input(tone):
    r = runner.invoke(audio_app, ["speed", str(tone), "--rate", "1.5"])
    assert r.exit_code == 0, r.output
    out = tone.with_name(f"{tone.stem}-1.5x{tone.suffix}")
    assert out.exists(), f"expected {out.name}; got {[p.name for p in tone.parent.iterdir()]}"
    assert out != tone, "the default output must never clobber the source"
    assert _duration(out) == pytest.approx(_duration(tone) / 1.5, rel=0.1)


@requires_ffmpeg
def test_slowed_verb_json_is_machine_readable(tone):
    import json

    r = runner.invoke(audio_app, ["slowed", str(tone), "--rate", "0.9", "--no-reverb", "--json"])
    assert r.exit_code == 0, r.output
    payload = json.loads(r.output)
    assert payload["pitch_shifted"] is True
    assert payload["rate"] == 0.9
    assert Path(payload["path"]).exists()


def test_a_zero_rate_exits_nonzero_with_a_message_not_a_traceback(tmp_path):
    src = tmp_path / "x.wav"
    src.write_bytes(b"RIFF")
    r = runner.invoke(audio_app, ["speed", str(src), "--rate", "0"])
    assert r.exit_code != 0, "a nonsense rate must not report success"
    assert "Traceback" not in r.output


def test_a_missing_file_is_refused_by_the_verb(tmp_path):
    r = runner.invoke(audio_app, ["speed", str(tmp_path / "nope.wav"), "--rate", "1.5"])
    assert r.exit_code != 0
