"""Hand the vaulted TikTok session to yt-dlp, without leaving it lying around.

`navig tt login` vaults a Playwright ``storage_state``. Until now that session
reached only the **browser** tier: `_download_mixed` passed ``session_host`` to the
photo path and called ``engine.download_urls`` — the yt-dlp video path — with no
session and no cookies at all. So a login could not unlock an age-gated ``/video/``
post, which is exactly what the operator tried to do.

yt-dlp reads cookies from a **file**, so bridging the two means the session touches
the disk. The vault exists to keep it encrypted at rest, so the exposure is kept as
small as the mechanism allows:

* written to the OS temp dir, never the config dir — it is not state, it is scratch;
* a random name, created with **owner-only permissions** before any content is
  written (`set_owner_only_file_permissions` — chmod 0600, or an icacls ACL on
  Windows);
* **deleted at process exit**, and the path is never logged;
* built **only** when a session is actually saved and the caller has not supplied
  cookies of its own, so it costs nothing on an anonymous install.

One file per process, not per call: every button on a shared link would otherwise
write and delete its own copy, multiplying the window for no benefit.
"""

from __future__ import annotations

import atexit
import logging
import os
import tempfile
from typing import Any

logger = logging.getLogger(__name__)

#: Netscape cookies.txt wants this exact first line; yt-dlp rejects the file without it.
_HEADER = "# Netscape HTTP Cookie File\n# Generated by navig — ephemeral, deleted on exit\n"

_cached_path: str | None = None


def _netscape_lines(cookies: list[dict[str, Any]]) -> list[str]:
    """Playwright cookies → Netscape rows, skipping any that cannot be expressed."""
    rows: list[str] = []
    for c in cookies or []:
        name, domain = c.get("name"), c.get("domain")
        if not name or not domain:
            continue
        # A leading dot is Netscape's "include subdomains" flag; Playwright encodes
        # the same thing the same way, so the two agree without translation.
        include_sub = "TRUE" if str(domain).startswith(".") else "FALSE"
        secure = "TRUE" if c.get("secure") else "FALSE"
        # Playwright uses -1 for a session cookie; Netscape wants 0, and yt-dlp
        # treats 0 as "no expiry recorded" rather than "expired in 1970".
        expires = c.get("expires")
        try:
            expiry = int(float(expires)) if expires is not None else 0
        except (TypeError, ValueError):
            expiry = 0
        if expiry < 0:
            expiry = 0
        rows.append("\t".join([
            str(domain), include_sub, str(c.get("path") or "/"),
            secure, str(expiry), str(name), str(c.get("value") or ""),
        ]))
    return rows


def _cleanup(path: str) -> None:
    try:
        os.unlink(path)
    except OSError:
        pass  # already gone, or the OS reaped the temp dir first


def vaulted_cookiefile(host: str = "tiktok.com") -> str | None:
    """Path to an ephemeral cookies.txt holding the vaulted session, or None.

    None whenever there is nothing to hand over — no vault, no saved session, or a
    session carrying no usable cookies. Callers treat None as "browse anonymously",
    which is the behaviour that predated this bridge, so a failure here can only
    cost the login — never the download.
    """
    global _cached_path
    if _cached_path and os.path.exists(_cached_path):
        return _cached_path
    try:
        from navig.vault.sessions import get_session  # noqa: PLC0415

        state = get_session(host)
        cookies = (getattr(state, "storage_state", None) or {}).get("cookies") if state else None
        rows = _netscape_lines(cookies or [])
        if not rows:
            return None

        fd, path = tempfile.mkstemp(prefix="navig-tt-", suffix=".cookies.txt")
        os.close(fd)
        # Harden BEFORE writing: creating the file world-readable and tightening it
        # afterwards leaves a window where the session is on disk and readable.
        from navig.core.file_permissions import set_owner_only_file_permissions  # noqa: PLC0415

        set_owner_only_file_permissions(path)
        with open(path, "w", encoding="utf-8", newline="\n") as fh:
            fh.write(_HEADER)
            fh.write("\n".join(rows) + "\n")

        atexit.register(_cleanup, path)
        _cached_path = path
        logger.debug("tiktok: handed %d vaulted cookies to yt-dlp (ephemeral file)", len(rows))
        return path
    except Exception as exc:  # noqa: BLE001 — anonymous is a working fallback; a crash is not
        logger.debug("tiktok: no vaulted session for yt-dlp: %s", exc)
        return None
